on:
  workflow_call:
jobs:
  Test:
    # runs-on: ubuntu-latest
    runs-on: gha-runner-scale-set
    container: openjdk:17-jdk-alpine3.14
    steps:
      - name: Update Repo
        run: apk update && apk upgrade

      - name: AddAPK
        run: apk --no-cache add git jq tar openssh

      - name: CheckOut
        uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          submodules: false   #set-safe-directory option of checkout didn't work
          fetch-depth: 0
          token: ${{ secrets.EPASS_GIT_TOKEN }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.EPASS_GIT_USER }}
          git config --global user.email ${{ secrets.EPASS_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: CheckCRCSubmodule
        run: |
          echo "Check central-common"
          if cat .gitmodules | grep central-common > /dev/null ; then
            rm -rf central-common
            git submodule add --force --name central-common https://${{ secrets.CRC_GIT_USER }}:${{ secrets.CRC_GIT_TOKEN }}@github.com/digital-ventures/crc-common central-common
            echo -e "\e[92m central-common is added \e[0m"
          else
            echo -e "\e[31m central-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckB2PSubmodule
        run: |
          echo "Check b2p-common"
          if cat .gitmodules | grep b2p-common > /dev/null ; then
            rm -rf b2p-common
            git submodule add --force --name b2p-common https://${{ secrets.B2P_GIT_USER }}:${{ secrets.B2P_GIT_TOKEN }}@github.com/digital-ventures/b2p-common b2p-common
            echo -e "\e[92m b2p-common is added \e[0m"
          else
            echo -e "\e[31m b2p-common is not found \e[0m"
          fi
        continue-on-error: true
      - name: ChecktepSubmodule
        run: |
          echo "Check tep-common"
          if cat .gitmodules | grep tep-common > /dev/null ; then
            rm -rf tep-common
            git submodule add --force --name tep-common https://${{ secrets.EPASS_GIT_USER }}:${{ secrets.EPASS_GIT_TOKEN }}@github.com/digital-ventures/tep-common tep-common
            echo -e "\e[92m tep-common is added \e[0m"
          else
            echo -e "\e[31m tep-common is not found \e[0m"
          fi
        continue-on-error: true

      - name: CheckSubmoduleExited
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".gitmodules"

      - name: UpdateSubmodule
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          git submodule update --remote -f --init
          git checkout HEAD .gitmodules
        continue-on-error: true

      - name: DockerLoginB2P
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}

      - name: DockerLoginCFD
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.EPASS_ACR_REGISTRY }}
          username: ${{ secrets.EPASS_ACR_USER }}
          password: ${{ secrets.EPASS_ACR_TOKEN }}

      - name: SonarQubeScan
        if: contains(github.ref_name, 'SONAR')
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.EPASS_SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.EPASS_SONARQUBE_HOST_URL }}
          LC_ALL: "en_US.UTF-8"
        with:
          projectBaseDir: src
          args: >
            -Dsonar.projectName=CFD-${{ secrets.EPASS_SERVICENAME }}
            -Dsonar.projectKey=${{ secrets.EPASS_SERVICENAME }}

      - name: PreCleanTest
        run: |
          apk add --no-cache ttf-dejavu fontconfig 
          ln -s /usr/lib/libfontconfig.so.1 /usr/lib/libfontconfig.so
          ln -s /lib/libuuid.so.1 /usr/lib/libuuid.so.1
          ln -s /lib/libc.musl-x86_64.so.1 /usr/lib/libc.musl-x86_64.so.1

      - name: CleanTest
        uses: gradle/gradle-build-action@v2
        env: 
          LD_LIBRARY_PATH: /usr/lib
        with:
          gradle-version: 7.2
          arguments: |
              clean test
