on:
  workflow_call:
jobs:
  BuildAndRelease:
    # runs-on: ubuntu-latest
    runs-on: [self-hosted, b2p]
    # container: node:16.13.0-alpine
    container: docker:20.10.21-alpine3.16
    steps:
      - name: AddAPK
        run: apk --no-cache add git jq tar openssh curl

      - uses: actions/checkout@v3
        with: 
          ssh-key: "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh-strict: 'StrictHostKeyChecking=no'
          # submodules: 'true'   #set-safe-directory option of checkout didn't work

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: GitConfig
        run: |
          git config --global user.name ${{ secrets.EPASS_GIT_USER }}
          git config --global user.email ${{ secrets.EPASS_GIT_USER }}@dv.co.th
          git config --global --add safe.directory ${GITHUB_WORKSPACE}

      - name: SetupDockerBuildx
        uses: docker/setup-buildx-action@v2

      - name: DockerLoginB2P
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.B2P_ACR_REGISTRY }}
          username: ${{ secrets.B2P_ACR_USER }}
          password: ${{ secrets.B2P_ACR_TOKEN }}

      - name: DockerLoginCFD
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.EPASS_ACR_REGISTRY }}
          username: ${{ secrets.EPASS_ACR_USER }}
          password: ${{ secrets.EPASS_ACR_TOKEN }}

      - name: BuildAndPush
        if: "!contains(github.ref_name, 'SONAR')"
        env:
          DOCKER_BUILDKIT: 1
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          echo ${{ github.ref_name }} > ./src/version.txt  #add content in /version page
          docker build --ssh default -t ${{ secrets.EPASS_ACR_REGISTRY }}/frontend/${{ secrets.EPASS_SERVICENAME }}:${{ github.ref_name }} .
          docker push ${{ secrets.EPASS_ACR_REGISTRY }}/frontend/${{ secrets.EPASS_SERVICENAME }}:${{ github.ref_name }}

      - name: BuildAndPushWithCodeScan
        if: "contains(github.ref_name, 'SONAR')"
        uses: docker/build-push-action@v3
        id: docker_build_sonar
        with:
          context: .
          file: DockerfileSonarqube
          build-args: SONARQUBE_TOKEN=${{ secrets.EPASS_SONARQUBE_TOKEN }}, CI_COMMIT_TAG=${{ github.ref_name }}
          push: true
          tags: ${{ secrets.EPASS_ACR_REGISTRY }}/frontend/${{ secrets.EPASS_SERVICENAME }}:${{ github.ref_name }}
